---
title: "The White Wine Quality"
author: 
  - Suleymanzade Savalan[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 20080795, [Github Repo](https://github.com/Suleymanzade1/Midterm)


# Introduction

The White Wine Quality Dataset is a publicly available dataset that contains information about the physicochemical properties of various types of white wines. The dataset is available on the UCI Machine Learning Repository, which is a widely used repository for datasets for machine learning research.

## Literature Review

The dataset has been used in various studies on white wine quality and machine learning. In one study, Cortez et al. @cortez2009modeling used the dataset to analyze the relationship between white wine quality and the various physicochemical properties of the wine. They used different machine learning algorithms, such as decision trees and artificial neural networks, to predict the quality of the wine based on these physicochemical properties. They found that the most important factors that influence white wine quality were alcohol content and volatile acidity.

In another study, Fernández-Delgado et al. @fernandez2014do compared the performance of several machine learning algorithms on this dataset. They used algorithms such as k-nearest neighbors, support vector machines, decision trees, and random forests, and found that random forests and support vector machines had the best performance.

In a more recent study, Tomescu et al. @tomescu2018predicting used this dataset to predict white wine quality using deep learning algorithms. They used a combination of convolutional neural networks and long short-term memory networks to predict the wine quality, achieving a mean squared error of 0.43.

In another study, Fernández et al. @fernandez2017new used this dataset to develop a new methodology for assessing the quality of wines. They used a combination of clustering techniques and expert knowledge to develop a new wine quality index, which they compared to the traditional wine quality ratings.

In a study by Maučec et al. @maucec2018prediction, this dataset was used to develop a method for predicting wine quality based on sensor data from electronic noses. They used various machine learning algorithms, including artificial neural networks and support vector machines, and achieved a prediction accuracy of over 90%.

Finally, in a study by Rodrigues et al. @rodrigues2018impact, this dataset was used to investigate the effect of climate change on wine quality. They analyzed the relationship between the physicochemical properties of the wine and the climate variables, such as temperature and precipitation, and found that changes in temperature and precipitation can have a significant impact on wine quality.

In conclusion, the White Wine Quality Dataset is a valuable resource for machine learning research and has been used in various studies to predict wine quality and develop new methodologies for assessing wine quality.



\newpage
# References {#references}
<div id="refs"></div>

